# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 521db5eda614257611163c927e01f32c01d59fa9269fb5abf00d44d7819cbd6de3546ddbca942096cad66f411527de349efdfe889bf928ef2f0a4fb75c5bd129

test:
  secret_key_base: 009060fe017f3ed6494c20d38f7791d5e635dd448830db84eac044c25a22cd148648323a84e21f26301c73e158b6ef5daa89b90affbf29769140d110f0ce07db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
